config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:show, :create, :new]
  
  resources :tasks do
    member do
      get 'status'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user #user(1)に対してtask(多)の関係を表している
  
  validates :content, presence: true, length: {maximum:255}
  validates :status, presence: true, length: {maximum:10}

end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email.downcase!}
  
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
            format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, 
            uniqueness: {case_sensitive: false}
            
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
        redirect_to login_path
    end
  end
  
  def counts(user)
      @count_tasks = user.tasks.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインしました'
      redirect_to @user
    else
      flash.now[:danger] = 'ログイン出来ませんでした'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  before_action :correct_user, only: [:show, :destroy, :edit, :update]
  
  def index
    if logged_in?
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page])
    end
  end
  
  def show
    @task = Task.find(params[:id])
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = '新しいタスクが作られました'
      redirect_to tasks_path
    else
      flash.now[:danger] = 'ERRORが起きました。やり直して下さい'
      render :new
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = 'タスクが更新されました'
      redirect_to tasks_path
    else
      flash.now[:danger] = 'ERRORが起きました。やり直して下さい'
      render :edit
    end
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    flash[:success] = 'タスクが削除されました'
    redirect_to @task
  end
  
  private
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
    redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
    
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録が出来ました'
      redirect_to @user
    else
      flash.now[:danger] = '登録できませんでした。やり直して下さい'
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def destroy
    
  end

  
private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, task| %>
  <div class="alert alert-<%= message_type %>"><%= task %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
      <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">My Task, ToDo</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'プロフィール', user_path(current_user) %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="false">メニュー<span class="caret"></span></a>
                <ul class="dropdown-menu"> <!--なぜか開かない-->
                  <li><a href="#">###</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </ul> 
              </li>
          <% else %>
            <li><%= link_to  '新規登録', signup_path %></li>
            <li><%= link_to  'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    
    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_message' %>

    
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <%= form_for(@task) do |f| %>
  
      <% if @task.errors.any? %>
        <div class="alert warning">
          <ul>
            <% @task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= f.label :content, 'タスク内容' %>
        <%= f.text_area :content, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.select :status, [["(未)","0"],["(完)","1"]], {include_blank: '選択して下さい'} %>
      </div>
      <%= f.submit 'OK', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% if logged_in? %>
<p>Your Task List</p>
  <% if @tasks.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>内容</th>
          <th>状態</th>
        </tr>
      </thead>
      <tbody>
        <% array =["(未)","(完)"] %>
        <% @tasks.each do |task| %>
        <tr>
            <td><%= task.id %>
            <td><%= link_to task.content, task %></td>
            <td><%= array[task.status.to_i] if task.status != nil %></td>
            <td><%= link_to '[編集]', edit_task_path(task) %>
            <%= link_to '[削除]', task, method: :delete, data: {confirm: '本当に削除しますか？'} %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <%= paginate @tasks %>
    </div>
  <% end %>

    <%= link_to '新規作成', new_task_path, class: 'btn btn-primary' %>
  
<% else %>

<h1>TaskListアプリです</h1>

  <%= link_to  '新規登録', signup_path, class: 'btn btn-primary' %>
  <%= link_to  'ログイン', login_path, class: 'btn btn-primary' %>
<% end %>

app/views/tasks/new.html.erb
<h1>新しいタスク</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.id %>個目のタスク</h1>


<% array =["(未)","(完)"] %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>内容</th>
      <th>状態</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.content %></td>
      <td><%= array[@task.status.to_i] if @task.status != nil %></td>
    </tr>
  </tbody>
</table>
<p></p>



<%= link_to '[編集]', edit_task_path(@task), class: 'btn btn-primary' %>
<%= link_to '[削除]', @task, method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-danger'  %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-5">
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <h3 class="panel panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel panel-body">
        <a href="#">画像</a>
      </div>
    </div>
  </aside>
  <div class="col-xs-7">
    <ul>
      <li>name</li>
      <li>email</li>
      <li><a href="#">プロフィール編集</a></li>
    </ul>
  </div>
  <div class="col-xs-7 col-xs-offset-5">
    <ul>
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>タスク <span class="badge"><%= @count_tasks %></span><% end %></li>
    </ul>
  </div>
</div>